### ISSUE TITLE
채팅 기록 파일 저장

### ISSUE THREAD

**Issue by emoee** [emoee/ChatGUI#29]
# 2024/01/04
현재 상황
maxLines(40)보다 크면 맨앞부터 내용이 지워지고 파일로 저장되는 방식으로 구현(실제 동작하는지 테스트 필요)

1. 드래그 방식으로 파일 저장
JTextField가 JTextComponent를 상속받아 구현되어있어서 드래그로 파일 저장 가능

2. 팝업 선택 방식으로 파일 저장
JDialog(팝업창)에 리스트박스 2개 생성해 시작과 끝을 입력. 해당 범위의 줄만 파일로 저장하도록 구현.

**Comment by chanhyuk0919** [comment]
구현 완료(SaveBtn class )
-사용자가 저장버튼을 누르면 Start Line과 End Line 입력 dialog 생성 

 1. line을 입력시 원하는 라인의 대화내용 저장
 2. empty 시 모든 대화내용 저장
 
-디렉토리 선택후 파일 이름 입력시 저장 완료
