### ISSUE TITLE
온라인 상태표시 

### ISSUE THREAD

**Issue by chanhyuk0919** [emoee/ChatGUI#33]
## 기능 요구 사항: 사용자의 **온라인 상태** 표시 변경

상세설명:

1. ChatUser에 상태를 저장할 수 있는 변수를 추가하여 해당 변수를 통해 제어.
2. Client는 GUI를 통해 서버에 자신의 상태를 변경을 요청. 
3. 서버는 해당 사용자의 상태를 확인해 모든 클라이언트에게 사용자의 상태 변경을 알림.
4. 모든 클라이언트는 변경된 상태를 받아 GUI에 표시.

필수데이터:
User id, User status

- 구현 리스트 
- [x] ChatUser 상태 변수 추가
- [x] 상태 변경 요청 서버 전송
- [x] 서버에서 사용자 목록 중 요청 전송한 사용자 찾아 id 저장
- [x] 요청한 사용자 id를 모든 사용자에게 전송
- [x] 요청한 사용자 상태 변수 변경
- [x] 사용자 목록 GUI 변경

**Comment by emoee** [comment]
- 구현 리스트 
- [ ] ChatUser 상태 변수 추가
- [ ] 상태 변경 요청 서버 전송
- [ ] 서버에서 사용자 목록 중 요청 전송한 사용자 찾아 id 저장
- [ ] 요청한 사용자 id를 모든 사용자에게 전송
- [ ] 요청한 사용자 상태 변수 변경
- [ ] 사용자 목록 GUI 변경

**Comment by emoee** [comment]
## **구현 완료: 사용자의 온라인 상태 표시**
사용자 목록을 받아와서 각 사용자의 상태에 따라 "ON" 또는 "OFF"를 표시하고, 이를 리스트에 추가하였다.

1. ChatUser에 status변수를 추가하여 해당 변수로 **사용자의 상태를 저장**하였다.
2. 사용자가 GUI의 onOff버튼을 클릭하게 되면 서버로 상태 **변경 요청**이 들어가고 
3. 서버는 명령을 처리해 **모든 클라이언트**에게 사용자의 상태 변경을 전달해주게 된다. 
4. **GUI**에는 사용자 이름 옆에  **ON, OFF** 표시가 나타나게 된다.
