### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by uiheonn** [emoee/ChatGUI#35]
1. 사용자 목록, 온라인 상태 목록을 구현하기 위해 MyList, OnList를 생성
1-1. MyList는 UserList, OnList의 상위 클래스
2. UserList, OnList는 MyList를 상속받은 클래스
3. OnList에서 사용자의 status를 확인 후 GUI에 출력

**Comment by uiheonn** [comment]
1. MyList는 JList를 상속
2. UserList에는 드래그엔드롭 기능과 사용자 이름을 보여줌
3. OnList에는 사용자 상태를 보여줌
4. UserList, OnList의 불필요한 메서드 제거함

1) 클라이언트 접속 시 팝업을 통해 ip와 포트번호를 입력하도록 수정
2) 버튼 수정 - connect : 체크, whisper : 귀

**Comment by emoee** [comment]
**OnList의 사용자 상태 수정**
사용자의 상태를 버튼을 통해 실시간으로 반영되도록 수정하였다.
ON, OFF로 사용자의 상태를 나타낸다.
