### ISSUE TITLE
채팅 이름 유효성 검사

### ISSUE THREAD

**Issue by emoee** [emoee/ChatGUI#43]
### 구현 내용:  채팅 이름 중복 방지 기능 추가
채팅 참여자들의 채팅 이름이 중복되지 않도록 하기 위한 기능 추가.

- [x] 채팅 참여자의 이름 중복 여부 확인
- [x] 중복되지 않는 이름일 경우 참여 허용
- [x] 중복된 이름일 경우 팝업 메시지를 보여준 후 사용자에게 다른 이름을 입력하도록 안내
- [x] 중복 여부 확인 후 처리

**Comment by uiheonn** [comment]
- 사용자가 동일한 닉네임을 입력한 경우 동작 과정
1. 동일한 사용자가 존재한다는 에러 메시지 팝업을 출력
2. 닉네임을 다시 입력하는 팝업 생성
3. 올바른 닉네임을 입력할 때 까지 반복
